# Generated by Django 3.0.1 on 2020-09-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('device_ip', models.CharField(max_length=32, null=True, verbose_name='设备ip')),
                ('device_name', models.CharField(max_length=32, null=True, verbose_name='设备ip')),
                ('device_port', models.CharField(max_length=8, null=True, verbose_name='设备端口')),
                ('file_path', models.CharField(max_length=128, null=True, verbose_name='文件路径')),
                ('status', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('describe', models.TextField(null=True, verbose_name='描述')),
                ('gmt_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
