# Generated by Django 3.0.1 on 2020-09-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicesysinfo'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='device_ip',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='device_port',
        ),
        migrations.AddField(
            model_name='audio',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceList'),
        ),
    ]
