# Generated by Django 3.0.1 on 2020-09-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200926_1841'),
        ('audio', '0002_auto_20200924_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='device.DeviceList'),
        ),
    ]
