# Generated by Django 3.0.1 on 2020-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_remove_audiolist_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolist',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
