# Generated by Django 3.0.1 on 2020-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20201002_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolist',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='名称'),
        ),
    ]
