# Generated by Django 3.0.1 on 2020-09-20 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=32, null=True, verbose_name='设备id')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='设备名')),
                ('ip', models.CharField(max_length=16, null=True, verbose_name='设备IP')),
                ('mac_addr', models.CharField(max_length=64, null=True, verbose_name='网卡物理地址')),
                ('port', models.CharField(max_length=8, null=True, verbose_name='设备端口号')),
                ('security_key', models.CharField(max_length=64, null=True, verbose_name='设备密钥')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '停机'), ('error', '异常'), ('unknown', '未知'), ('other', '其他')], max_length=16, verbose_name='状态')),
                ('fft_points', models.IntegerField(null=True, verbose_name='FFT点数参数')),
                ('output_gain', models.IntegerField(null=True, verbose_name='输出增益参数')),
                ('mic_direction', models.CharField(max_length=32, null=True, verbose_name='麦克风头指向参数')),
                ('output_channel', models.IntegerField(null=True, verbose_name='音频输出通道编号')),
                ('audio_encoder', models.IntegerField(null=True, verbose_name='编码器ID')),
                ('audio_channels', models.IntegerField(null=True, verbose_name='音频声道数')),
                ('audio_sample_rate', models.IntegerField(null=True, verbose_name='音频采样率')),
                ('audio_frame_size', models.IntegerField(default=160, null=True, verbose_name='音频帧长')),
                ('audio_bitrate', models.IntegerField(null=True, verbose_name='音频编码器的比特率')),
                ('retrans_timeout', models.IntegerField(default=100, null=True, verbose_name='重传超时阈值')),
                ('device_position', models.CharField(max_length=100, null=True, verbose_name='设备位置')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('gmt_modify', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('remarks', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('device_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.DeviceGroup')),
            ],
        ),
    ]
