# Generated by Django 3.0.1 on 2020-09-23 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSysInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_ver', models.CharField(max_length=64, verbose_name='固件版本')),
                ('sw_ver', models.CharField(max_length=64, verbose_name='软件版本')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('running_time', models.TimeField(verbose_name='运行时间')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('gmt_modify', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
    ]
