# Generated by Django 3.0.1 on 2020-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicesysinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelist',
            old_name='ip',
            new_name='ip_addr',
        ),
        migrations.AddField(
            model_name='devicelist',
            name='dns_server1',
            field=models.CharField(max_length=16, null=True, verbose_name='dns server 1'),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='dns_server2',
            field=models.CharField(max_length=16, null=True, verbose_name='dns server 2'),
        ),
    ]
