# Generated by Django 3.0.1 on 2020-09-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20200925_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='audio_sample_bits',
            field=models.IntegerField(null=True, verbose_name='每个采样的 bit 数'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='device_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device.DeviceGroup'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='gmt_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='output_gain',
            field=models.IntegerField(default=8, null=True, verbose_name='输出增益参数'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '停机'), ('error', '异常'), ('unknown', '未知'), ('other', '其他')], default='running', max_length=16, verbose_name='状态'),
        ),
    ]
