# Generated by Django 3.0.1 on 2020-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200926_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesysinfo',
            name='fw_ver',
        ),
        migrations.RemoveField(
            model_name='devicesysinfo',
            name='running_time',
        ),
        migrations.RemoveField(
            model_name='devicesysinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='devicesysinfo',
            name='sw_ver',
        ),
        migrations.AddField(
            model_name='devicelist',
            name='fw_ver',
            field=models.CharField(max_length=64, null=True, verbose_name='固件版本'),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='product_id',
            field=models.CharField(max_length=64, null=True, verbose_name='产品ID'),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='running_time',
            field=models.TimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='sw_ver',
            field=models.CharField(max_length=64, null=True, verbose_name='软件版本'),
        ),
    ]
