# Generated by Django 3.0.1 on 2020-09-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200930_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelist',
            old_name='name',
            new_name='device_name',
        ),
    ]
