# Generated by Django 3.0.1 on 2020-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200930_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='product_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='产品ID'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='status',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'processing'), (2, 'error')], default=0, verbose_name='状态'),
        ),
    ]
