# Generated by Django 3.0.1 on 2020-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20201001_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='status',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'processing'), (2, 'recording'), (3, 'error')], default=0, verbose_name='状态'),
        ),
    ]
