# Generated by Django 3.0.1 on 2020-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20201002_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='audio_bitrate',
            field=models.IntegerField(null=True, verbose_name='音频编码器比特率'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='audio_channels',
            field=models.IntegerField(default=1, null=True, verbose_name='音频声道数'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='audio_encoder',
            field=models.IntegerField(default=3, null=True, verbose_name='编码器ID'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='audio_frame_size',
            field=models.IntegerField(default=320, null=True, verbose_name='音频帧长'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='audio_sample_bits',
            field=models.IntegerField(default=24, null=True, verbose_name='采样位数'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='audio_sample_rate',
            field=models.IntegerField(default=16000, null=True, verbose_name='音频采样率'),
        ),
        migrations.AlterField(
            model_name='devicelist',
            name='retrans_timeout',
            field=models.IntegerField(default=1000, null=True, verbose_name='重传超时阈值'),
        ),
    ]
