# Generated by Django 3.0.1 on 2020-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20201004_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelist',
            name='audio_channels',
        ),
        migrations.AddField(
            model_name='devicelist',
            name='output_channel',
            field=models.IntegerField(null=True, verbose_name='音频输出通道编号'),
        ),
    ]
