# Generated by Django 3.0.1 on 2020-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20201004_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='status',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'processing'), (2, 'recording'), (3, 'error')], default=1, verbose_name='状态'),
        ),
    ]
