# Generated by Django 3.0.1 on 2020-10-07 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_version', models.CharField(blank=True, max_length=12, null=True, verbose_name='固件版本')),
                ('software_version', models.CharField(blank=True, max_length=12, null=True, verbose_name='软件版本')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUpgradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=12, null=True, verbose_name='升级版本')),
                ('firmware_version', models.CharField(blank=True, max_length=12, null=True, verbose_name='固件版本')),
                ('software_version', models.CharField(blank=True, max_length=12, null=True, verbose_name='软件版本')),
                ('gmt_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='升级时间')),
            ],
        ),
    ]
