# Generated by Django 3.0.1 on 2020-10-07 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='消息内容')),
                ('gmt_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('unread', models.BooleanField(default=True, verbose_name='未读')),
                ('msg_type', models.IntegerField(choices=[(1, '通知'), (2, '系统')], default=1, verbose_name='消息类型')),
            ],
        ),
    ]
