# Generated by Django 3.0.1 on 2020-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_systemmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessage',
            name='user',
        ),
    ]
